'blank_issues_enabled': true
'contact_links':
  - 'about': >
        Please check AdGuard VPN Knowledgebase for more useful information about our products
    'name': 'Knowledgebase'
    'url': 'https://adguard-vpn.com/kb/'